apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod-edc
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: isaac.soriano-tapia@materna.group
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            ingressClassName: nginx