apiVersion: v1
kind: PersistentVolume
metadata:
  name: gaiaxdata
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 500Mi
  hostPath:
    path: /mnt/shared_data/gaiax
    type: Directory
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-storage
  volumeMode: Filesystem